apiVersion: template.openshift.io/v1
kind: Template
metadata:
name: "apicast-xml-policy"
message: "APIcast XML Policy"
description: "Builds APIcast with xml policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${IMAGE_STREAM_NAME}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${BUILD_NAME}'
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: '${IMAGE_STREAM_NAME}:${IMAGE_STREAM_TAG}'
    source:
      git:
        uri: https://github.com/3scale-qe/apicast-json-to-xml.git
        ref: 'master'
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          namespace: '${NAMESPACE}'
          name: 'amp-apicast:${AMP_RELEASE}'

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. "2.10"), "master" for nightlies
- name: BUILD_NAME
  required: true
  description: Name of the build config
- name: IMAGE_STREAM_NAME
  required: true
  description: Name of the target image stream
- name: NAMESPACE
  required: true
  description: Namespace where amp-apicast resides
- name: IMAGE_STREAM_TAG
  required: false
  default: "latest"
