apiVersion: template.openshift.io/v1
kind: Template
metadata:
name: "apicast-failing-policy"
message: "APIcast Failing Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${IMAGE_STREAM_APICAST_POLICY}'

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${IMAGE_STREAM_AMP_APICAST_CUSTOM_POLICY}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${BUILD_NAME_FAILING_POLICY}'
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: '${IMAGE_STREAM_APICAST_POLICY}:failing'
    source:
      git:
        uri: https://github.com/3scale-qe/apicast-failing-policy.git
        ref: 'main'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: '${BUILD_NAME_CUSTOM_POLICY}'
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${IMAGE_STREAM_AMP_APICAST_CUSTOM_POLICY}:latest'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: '${IMAGE_STREAM_APICAST_POLICY}:failing'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/failing
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. "2.10"), "master" for nightlies
- name: BUILD_NAME_FAILING_POLICY
  required: true
  description: name of build config for building an image to IMAGE_STREAM_APICAST_POLICY
- name: BUILD_NAME_CUSTOM_POLICY
  required: true
  description: name of build config for creating new APIcast image copying just necessary code from that previous image
- name: IMAGE_STREAM_APICAST_POLICY
  required: true
  description: name of an image stream for the custom apicast policy
- name: IMAGE_STREAM_AMP_APICAST_CUSTOM_POLICY
  required: true
  description: name of an image stream for the apicast modified with the custom policy