#!/usr/bin/env python


from subprocess import run, PIPE
import sys

from packaging.version import Version, InvalidVersion


tags = run(["git", "tag"], check=False, encoding="utf-8", stdout=PIPE)
tags = tags.stdout.split()

version = Version(open("VERSION").read().strip())

versions = []
for tag in tags:
    try:
        versions.append(Version(tag[1:]))
    except InvalidVersion:
        pass
latest = sorted(versions)[-1])

just_one = "-1" in sys.argv

def docker_tags(version, latest, just_one):
    version = str(version)  # X.Y.Z.R
    tags = [version]
    if just_one:
        return tags
    tags.append(version.rsplit(".", 1)[0])  # X.Y.Z
    if latest:
        tags.append(version.rsplit(".", 2)[0])  # X.Y
        tags.append(version.split(".")[0])
        tags.append("latest")
    return tags


if f"v{version}" in tags:
    print(" ".join(docker_tags(version, latest == version, just_one)))
    sys.exit(0)

rc = 1
current = f"v{version}rc{rc}"

while current in tags:
    rc += 1
    current = f"{version}rc{rc}"
print(current)
