#!/bin/sh
# docker-build image-name main-tag extra-tags...

imagename=$1
shift

tag=$1
shift

image=$imagename:$tag

buildargs=
test -n "$CACERT" && buildargs="--build-arg=cacert=$CACERT"

docker build -t $image $buildargs .

if [ -n "$PUSHIMAGE" ]; then
	docker push $image

	for tag in "$@"; do
		docker tag $image $imagename:$tag
		docker push $imagename:$tag
	done
fi
