#!/usr/bin/env python


from subprocess import run, PIPE
import sys

from packaging.version import Version, InvalidVersion


tags = run(["git", "tag"], check=False, encoding="utf-8", stdout=PIPE)
tags = tags.stdout.split()

version = open("VERSION").read().strip()

versions = []
for tag in tags:
    try:
        versions.append(Version(tag))
    except InvalidVersion:
        pass
latest = sorted(versions)[-1]

just_one = "-1" in sys.argv

def docker_tags(version, latest, just_one):
    tags = [version]
    if just_one:
        return tags
    tags.append(version.split("-")[0])
    tags.append(version.rsplit(".", 1)[0])
    tags.append(version.split(".")[0])
    if latest:
        tags.append("latest")
    return tags


if version in tags:
    print(" ".join(docker_tags(version, latest == Version(version), just_one)))
    sys.exit(0)

revision = version.split("-")[-1]
version = Version(version).base_version
rc = 1
current = f"{version}rc{rc}-{revision}"

while current in tags:
    rc += 1
    current = f"{version}rc{rc}-{revision}"
print(current)
