#!/usr/bin/env python

import argparse
import io
import os
import zipfile

from lxml import etree
import requests

aparser = argparse.ArgumentParser(description="Upload junit to reportportal")
aparser.add_argument("--reportportal", required=True, help="URL of reportportal")
aparser.add_argument("--project", required=True, help="reportportal project where to import")
aparser.add_argument("--launch-name", required=True, help="Desired launch name in reportportal")
aparser.add_argument("--token-variable", required=True, help="env variable with auth token")
aparser.add_argument("junitfile", nargs="+", help="junit file to import")
args = aparser.parse_args()

polish = etree.XSLT(etree.parse("./xslt/polish-junit.xsl"))

stream = io.BytesIO()

with zipfile.ZipFile(stream, mode="w", compression=zipfile.ZIP_DEFLATED) as azip:
    for junitfile in args.junitfile:
        content = etree.tostring(polish(etree.parse(junitfile)))
        azip.writestr(os.path.basename(junitfile), content)

token = os.environ[args.token_variable]
launch = args.launch_name
project = args.project
reportportal = args.reportportal.rstrip("/")

auth = {"Authorization": f"Bearer {token}"}
launch_import = f"{reportportal}/api/v1/{project}/launch/import"

print(requests.post(launch_import, files={"file": (f"{launch}.zip", stream.getbuffer(), "application/zip")}, headers=auth).text)
