#!/usr/bin/env python

from packaging.version import Version, InvalidVersion
from subprocess import run, PIPE
import sys

tags = run(["git", "tag"], check=False, encoding="utf-8", stdout=PIPE)
tags = tags.stdout.split()

versions = []

for tag in tags:
    try:
        versions.append(Version(tag))
    except InvalidVersion:
        pass

version = Version(sys.argv[1])

sys.exit(not(sorted(versions)[-1] == version and not(version.is_devrelease)))
