apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: servicemesh-httpbin
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        labels:
          app: ${NAME}
      spec:
        containers:
          - image: quay.io/jsmadis/httpbin:latest
            imagePullPolicy: IfNotPresent
            name: httpbin
            ports:
              - containerPort: 8080
    strategy:
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      deployment: ${NAME}
      app: ${NAME}
  spec:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
    selector:
     app: ${NAME}
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    hosts:
      - "*"
    gateways:
      - ${NAME}
    http:
      - match:
          - uri:
              prefix: /${NAME}
        rewrite:
          uri: "/"
        route:
          - destination:
              host: ${NAME}
              port:
                number: 8080
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
          - "*"
parameters:
- name: NAME
  description: "Name for the resources created"
  required: true