apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 3scale-adapter-rhsso-policy
objects:
- apiVersion: security.istio.io/v1beta1
  kind: RequestAuthentication
  metadata:
    name: ${NAME}
  spec:
    selector:
      matchLabels:
        app: ${TARGET}
    jwtRules:
    - issuer: ${ISSUER}
      jwksUri: ${JWKS}
parameters:
- name: NAME
  description: "Name of the policy"
  required: true
- name: ISSUER
  description: "Issuer url (http://keycloak-keycloak.34.242.107.254.nip.io/auth/realms/3scale-keycloak)"
  required: true
- name: JWKS
  description: "JWKSURL url (http://keycloak-keycloak.34.242.107.254.nip.io/auth/realms/3scale-keycloak/protocol/openid-connect/certs)"
  required: true
- name: TARGET
  description: "Target of the policy"
  value: "httpbin"
  required: true