apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: service-entry
objects:
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: ${NAME}
    labels:
      app: ${LABEL}
  spec:
    hosts:
    - ${HOST}
    ports:
    - number: 443
      name: https
      protocol: HTTPS
    location: MESH_EXTERNAL
    resolution: DNS
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: ${NAME}
    labels:
      app: ${LABEL}
  spec:
    host: ${HOST}
    trafficPolicy:
      tls:
        mode: SIMPLE
        sni: ${HOST}
parameters:
- name: NAME
  description: "Name of the service entry"
  required: true
- name: HOST
  description: "Host"
  required: true
- name: LABEL
  description: "App label for all resources"
  required: true