name: create release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Use x.y.z format e.g. 2.12.0"
        type: string
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pipenv
        run: pip install pipenv
      - name: Create release  
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          make clean release
          git push -u origin HEAD
          gh pr create --fill --reviewer mganisin,pehala
        env:
          VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
