name: create release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pip install pipenv
      - run: |
          make clean release
          git push -u origin HEAD
          gh pr create --fill --reviewer mganisin,pehala
        env:
          VERSION: ${{ github.event.inputs.version }}
