name: dispatch_1_rc_pullrequest
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: "Use x.y.z format e.g. 2.12.0 or KEEP EMPTY"
        type: string
jobs:
  dispatch_1_rc_pullrequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pipenv
        run: pip install pipenv
      - name: setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: make release
        run: make clean release
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: create PR
        run: |
          git push -u origin HEAD
          gh pr create -B stable-2.14 --fill --reviewer mkudlej,mdujava,dhlavac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
