name: dispatch_github_release
description: Verify RC build before this!
on:
  workflow_dispatch

jobs:
  dispatch_github_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: dispatch_github_release
        shell: bash
        run: gh release list --limit 1|awk '{print $1}'|xargs git show-ref|(read commit ref; ref=${ref##refs/tags/}; gh release create ${ref%%rc*} --generate-notes --target $commit)
        env:
          # github-actions account doesn't seem to trigger events, therefore different account must be used
          GITHUB_TOKEN: ${{ secrets.BOTBEZBOT_TOKEN }}
